# Generated by Django 4.1.7 on 2023-04-03 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='postEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('electronics', models.BooleanField(default=False)),
                ('clothing', models.BooleanField(default=False)),
                ('music', models.BooleanField(default=False)),
                ('furniture', models.BooleanField(default=False)),
                ('appliances', models.BooleanField(default=False)),
                ('toys_games', models.BooleanField(default=False)),
                ('auto_parts', models.BooleanField(default=False)),
                ('free', models.BooleanField(default=False)),
                ('anitques', models.BooleanField(default=False)),
                ('baby_kids_family', models.BooleanField(default=False)),
                ('books', models.BooleanField(default=False)),
                ('sporting', models.BooleanField(default=False)),
                ('jewelry', models.BooleanField(default=False)),
                ('s_date', models.DateField()),
                ('e_date', models.DateField()),
                ('s_time', models.TimeField()),
                ('e_time', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Ndeals',
        ),
    ]
